[phases.install]
cmds = [
  "rm -rf node_modules/.cache",
  "rm -rf dist",
  "npm ci --legacy-peer-deps --no-cache"
]

[phases.build]
cmds = [
  "rm -rf dist",
  "npm run build"
]

[start]
cmd = "npm run start"

[variables]
NODE_ENV = "production"
NIXPACKS_NO_CACHE = "1"
